---
title: "Programa de Prevención y Control del Dengue | 2024"
format: 
  dashboard:
    nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup}
library(sf)
library(mapgl)
library(mapboxapi)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
```


# [**Probabilidad de Casos Importados**]{style="font-size:2pt"}

::: panel-tabset

### [**Área Metropolitana de CDMX**]{style="color:#990000"}

```{r casos_importadis}

# Step 1. load the dengue sdm  ####
x <- terra::rast("/Users/fdzul/Dropbox/posdoctorado_INSP/proyectos/risk_mzmv/11.output/pred_dengue.tif")

# Step 2. load the aoi and dataset final ####
load("~/Dropbox/posdoctorado_INSP/proyectos/risk_mzmv/8.RData/results/ml_dengue/ml_dengue_cdmx.RData")
load("~/Dropbox/posdoctorado_INSP/proyectos/risk_mzmv/8.RData/area_of_interes/aoi.RData")


# Step3. extract the alcaldias of cdmx ####
mun <- rgeomex::AGEM_inegi19_mx[mzmv,]

mapview::mapview(x,
                 layer.name = "Probabilidad de Casos Importados",
                 na.color = NA,
                 col.regions = tidyterra::whitebox.colors(palette = "muted", 
                                                          n = 10,
                                                          rev = FALSE)) +
    mapview::mapview(mzmv,
                     layer.name = "Área Metropolitana",
                     alpha.regions = 0.,
                     legend = FALSE) +
    mapview::mapview(mun,
                     layer.name = "Municipios",
                     alpha.regions = 0.01,
                     legend = FALSE) +
    mapview::mapview(den_thin |> 
                         dplyr::filter(class == "presence"),
                     layer.name = "Presencia de Casos Importados",
                     col.regions = "#E01A59",
                     col = "white",
                     legend = FALSE)

```

:::


# [**Probabilidad de Vector**]{style="font-size:2pt"}

::: panel-tabset
```{r presencia_aedes}


# Step 1. load the sdm aedes ####
pred <- terra::rast("/Users/fdzul/Dropbox/posdoctorado_INSP/proyectos/risk_mzmv/11.output/pred_ae_aegypti.tif")

# Step 2. load the aoi and dataset final ####
load("~/Dropbox/posdoctorado_INSP/proyectos/risk_mzmv/8.RData/area_of_interes/aoi_aedes_thin.RData")

# Step3. extract the alcaldias of cdmx ####
mun <- rgeomex::AGEM_inegi19_mx[mzmv,]


mapview::mapview(pred,
                 layer.name = "Probabilidad de  Ae. aegypti",
                 na.color = NA,
                 col.regions = tidyterra::whitebox.colors(palette = "muted", 
                                                          n = 10,
                                                          rev = FALSE)) +
    mapview::mapview(mzmv,
                     layer.name = "Área Metropolitana",
                     alpha.regions = 0.,
                     legend = FALSE) +
    mapview::mapview(mun,
                     layer.name = "Municipios",
                     alpha.regions = 0.01,
                     legend = FALSE) +
    mapview::mapview(aegypti_thin |> 
                         dplyr::filter(class == "presence"),
                     layer.name = "Presencia de Ae. aeggypti",
                     col.regions = "#E01A59",
                     col = "white",
                     legend = FALSE)


```
:::


# [**Escenarios Epidemiológicos**]{style="font-size:2pt"}

::: panel-tabset

<link href='https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css' rel='stylesheet' />
```{r escenarios}
# Step 1. load the prediction ####
x <- terra::rast("/Users/fdzul/Dropbox/posdoctorado_INSP/proyectos/risk_mzmv/11.output/pred_class_risk.tif")

# Step 2. load aoi ####
load("~/Dropbox/posdoctorado_INSP/proyectos/risk_mzmv/8.RData/area_of_interes/aoi.RData")

# step 3. load of the alcaldias ####

# Step 3.1. load the pop total ciudad de mexico ####
y <- vroom::vroom("/Users/fdzul/Dropbox/datasets/inegi/scince/Población total Ciudad de México - 09101 por municipio_demarcación territorial.csv")

# Step 3.2. load the minicipalities ####
mun <- rgeomex::AGEM_inegi19_mx |>
    dplyr::filter(CVEGEO %in% c(y$cvegeo))

# Step 4. extract the alcaldias with hight prob ####
mun_high <- mun |>
    dplyr::filter(NOMGEO %in% c("Tlalnepantla de Baz",
                                "Azcapotzalco",
                                "Cuauhtémoc",
                                "Benito Juárez",
                                "Coyoacán",
                                "Venustiano Carranza",
                                "Iztacalco",
                                
                                "Naucalpan de Juárez",
                                "Miguel Hidalgo",
                                "Iztapalapa"))

library(mapgl)
library(htmlwidgets)

mapgl::mapboxgl(style = mapgl::carto_style("positron"),
                center = c(-99.127120, 19.393996),
                zoom = 8) |>
    mapgl::add_image_source(id = "raster-source", 
                            data = x,
                            colors = c("#1f78b4", "#33a02c", "#FFFEC6", "#E4744F","#e31a1c")) |>
    mapgl::add_raster_layer(id = "raster-layer", 
                            source = "raster-source",
                            raster_opacity = 0.5) |>
    mapgl::add_categorical_legend(
        legend_title = "Escenarios Epidemuiológicos",
        values = c("Riesgo Muy Alto", 
                   "Riesgo Alto",
                   "Riesgo Medio", 
                   "Riesgo Bajo", 
                   "Riesgo Muy Bajo"),
        colors = c("#e31a1c", "#E4744F","#FFFEC6", "#33a02c", "#1f78b4"),
        circular_patches = FALSE)
```

:::

